import {filterLogs} from './log-filter.js';
export function createLogView({esc,btn,showModal,field,selectField,getState}){
 let content='',paused=false,query='',level='',loading=false,error='';
 const filtered=()=>filterLogs(content,query,level);
 function paint(){const target=document.querySelector('#log-content');if(target){target.textContent=error||filtered()||(query||level?'Нет сообщений по выбранному фильтру':'Журнал пуст');}}
 async function refresh(){if(loading||paused||!document.querySelector('#log-content')||!window.APP_API)return;loading=true;try{content=await window.APP_API.Logs();error='';paint();}catch(e){error=e.message;paint();}finally{loading=false}}
 const page=()=>`<section class="logs-page"><header class="logs-header"><div><h2>Журнал ядра</h2><p>Последние 64 КБ · ${getState().logging?.enabled?'сбор включён':'сбор выключен'}</p></div><div class="logs-actions">${btn('Настройки','log-settings','settings')}${btn('Скачать ZIP','log-export','download')}</div></header><div class="logs-toolbar"><input id="log-search" class="search" aria-label="Поиск в журнале" placeholder="Поиск по сообщению, домену или процессу" value="${esc(query)}"><select class="route-select" id="log-level" aria-label="Минимальный уровень сообщений">${[['','Все сообщения'],['debug','Debug и выше'],['info','Info и выше'],['warning','Предупреждения и ошибки'],['error','Только ошибки']].map(([v,t])=>`<option value="${v}" ${v===level?'selected':''}>${t}</option>`).join('')}</select></div><div class="logs-controls"><span>${paused?'Обновление приостановлено':'Обновляется автоматически'}</span><div class="logs-actions">${btn('Скопировать','log-copy','code')}${btn(paused?'Продолжить':'Пауза','log-pause',paused?'refresh':'pause')}${btn('Очистить','log-clear','trash')}</div></div><pre class="log-content" id="log-content" tabindex="0" aria-label="Журнал Mihomo">${esc(error||filtered()||(query||level?'Нет сообщений по выбранному фильтру':'Журнал пуст'))}</pre><p class="logs-note">Копирование учитывает поиск и фильтр. ZIP содержит все сохранённые файлы.</p></section>`;

 function settings(){const s=getState().logging||{enabled:true,level:'info',maxSizeMB:5,files:5,days:7};showModal('Журнал ядра','Лимиты хранения применяются сразу. Уровень ядра — после переподключения.',selectField('Собирать журнал','enabled',[['true','Да'],['false','Нет']],String(s.enabled))+selectField('Уровень','level',['debug','info','warning','error','silent'].map(x=>[x,x]),s.level)+`<div class="field-grid">${field('Размер файла, МБ','maxSizeMB',s.maxSizeMB,'1–50 МБ','number')}${field('Всего файлов','files',s.files,'1–10, включая текущий','number')}</div>`+field('Хранить, дней','days',s.days,'1–30 дней','number'),f=>{getState().logging={enabled:f.get('enabled')==='true',level:f.get('level'),maxSizeMB:Number(f.get('maxSizeMB')),files:Number(f.get('files')),days:Number(f.get('days'))}})}
 document.addEventListener('input',e=>{if(e.target.id==='log-search'){query=e.target.value;paint()}});document.addEventListener('change',e=>{if(e.target.id==='log-level'){level=e.target.value;paint()}});
 setInterval(refresh,2000);
 return {page,settings,refresh,async copy(){const text=filtered();if(!text)throw Error('Нет сообщений для копирования');if(!await window.APP_API.CopyLogText(text))throw Error('Не удалось скопировать журнал');return 'Видимые логи скопированы';},toggle(){paused=!paused}};
}
