export function editSet({item,state,getState,showModal,field,selectField,esc,upsert}){
 const s=item||{id:crypto.randomUUID(),name:'',domains:[],keywords:[],processes:[],cidrs:[],resolvers:[],action:'DIRECT',enabled:true,realIP:true,bypassTUN:true};
 const switchField=(label,key,help)=>`<label class="set-toggle"><span><strong>${label}</strong><small>${help}</small></span><input type="checkbox" role="switch" name="${key}" ${s[key]?'checked':''}><span class="set-toggle-track" aria-hidden="true"></span></label>`;
 const list=(label,key,placeholder,help,examples)=>`<section class="set-section field list-editor" data-list="${key}"><h3>${label}</h3><p class="set-description">${help}</p><div class="list-values">${(s[key]||[]).map(v=>`<button type="button" class="list-token" data-value="${esc(v)}" aria-label="Удалить ${esc(v)}">${esc(v)} <span aria-hidden="true">×</span></button>`).join('')}</div><div class="process-picker-toolbar"><input aria-label="${label}" placeholder="${esc(placeholder)}"><button type="button" class="button list-add">Добавить</button></div><small class="set-example">${examples}</small></section>`;
 showModal(item?'Изменить набор':'Новый набор маршрутизации','Объедините связанные правила и DNS, чтобы включать их вместе.',`<div class="set-editor"><div class="set-basics">${field('Название набора','name',s.name,'Например, Ресурсы компании')}${switchField('Набор включён','enabled','Выключенный набор сохраняется, но не применяется.')}${selectField('Маршрут для доменов, IP и процессов','action',[['DIRECT','Напрямую — по маршрутам ОС'],['PROXY','Через VPN — сервер Mihomo'],['REJECT','Блокировать соединения']],s.action)}</div>
 <details class="set-cisco-example"><summary>Пример: доступ через Cisco</summary><div class="set-cisco-content"><p><strong>Домены:</strong> +.company.example, +.internal.example.</p><p><strong>DNS:</strong> 10.20.0.53 и 10.20.0.54, указанные в настройках виртуального адаптера Cisco. Это условные адреса: укажите DNS своего подключения, а не IP самого адаптера.</p><p><strong>Маршрутизация:</strong> выберите «Напрямую», включите «Реальные IP для доменов» и «Обход TUN». Добавьте рабочую подсеть, например 172.16.0.0/12. Её адреса и DNS набора пойдут по маршрутам ОС, включая маршруты Cisco.</p><p>Пример не заполняет поля автоматически. Если шлюз vpn.company.example входит в домены набора, задайте для него отдельный DNS, доступный до подключения Cisco.</p></div></details>
 <div class="set-grid">${list('Домены','domains','+.company.example','Соединения с этими доменами используют выбранный «Маршрут для доменов, IP и процессов». Их имена разрешаются через «DNS для доменов набора».','<strong>+.company.example</strong> — company.example и все поддомены. <strong>vpn.company.example</strong> — только этот адрес. Без https:// и пути страницы.')}
 ${list('DNS для доменов набора','resolvers','10.20.0.53','Эти DNS разрешают только имена из поля «Домены» этого набора. Они не назначаются приложениям и IP-подсетям. Пустой список не добавляет DNS-правил.','Например, <strong>10.20.0.53</strong> — DNS виртуального адаптера Cisco. Возьмите адрес из настроек своего подключения. Можно добавить несколько DNS.')}
 ${list('IP-адреса и подсети','cidrs','172.16.0.0/12','Адреса, к которым применяется маршрут набора. При включённом обходе TUN они исключаются из виртуального адаптера.','<strong>172.16.0.0/12</strong> — подсеть. <strong>10.20.0.53/32</strong> — один IPv4-адрес. Для одного IPv6 используйте /128.')}
 ${list('Часть доменного имени · необязательно','keywords','ubisoft','Маршрут применяется ко всем доменам, содержащим указанный текст. Эти условия не меняют DNS и Fake-IP.','<strong>ubisoft</strong> совпадёт с ubisoft.com и static.ubisoft.com. Это поиск фрагмента в имени домена, не URL и не маска.')}
 ${list('Приложения · необязательно','processes','chrome.exe','Маршрут для всего трафика указанных процессов, независимо от домена. Для набора рабочих сайтов можно оставить пустым.','Например, <strong>chrome.exe</strong> на Windows или точный путь к процессу на macOS. Маски задаются в отдельных правилах. Процесс Cisco добавлять ради доступа к рабочим сайтам не нужно.')}</div>
 <div class="set-grid set-options"><section class="set-section">${switchField('Реальные IP для доменов','realIP','Исключить домены этого набора из Fake-IP.')}<p class="set-description">Включено — DNS возвращает настоящие адреса для поля «Домены». Выключено — действует общий режим DNS.</p></section><section class="set-section">${switchField('Обход TUN','bypassTUN','Исключить IP-подсети набора и IP-адреса его DNS из адаптера Mihomo.')}<p class="set-description">Включено — трафик к исключённым IP идёт по маршрутам ОС, минуя Mihomo. Выбранный маршрут набора на этот трафик не действует. Выключено — набор не добавляет исключений TUN.</p></section></div><p class="set-order-note">Активные наборы проверяются сверху вниз, раньше отдельных правил. Используйте режим «По правилам». Сохранённые изменения применятся после перезапуска ядра.</p></div>`,f=>{const next={...s,name:f.get('name').trim(),action:f.get('action'),enabled:f.has('enabled'),realIP:f.has('realIP'),bypassTUN:f.has('bypassTUN')};for(const list of document.querySelectorAll('#modal-form [data-list]')){const values=[...list.querySelectorAll('[data-value]')].map(b=>b.dataset.value);const pending=list.querySelector('input').value.trim();if(pending)values.push(pending);next[list.dataset.list]=[...new Set(values)]}getState().sets ||= [];upsert(getState().sets,next)});
 const form=document.querySelector('#modal-form');form.querySelectorAll('[data-list]').forEach(list=>{const input=list.querySelector('input');const add=()=>{const v=input.value.trim();if(!v)return;const values=[...list.querySelectorAll('[data-value]')].map(x=>x.dataset.value);if(!values.includes(v))list.querySelector('.list-values').insertAdjacentHTML('beforeend',`<button type="button" class="list-token" data-value="${esc(v)}" aria-label="Удалить ${esc(v)}">${esc(v)} <span aria-hidden="true">×</span></button>`);input.value='';input.focus()};list.querySelector('.list-add').onclick=add;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();add()}};list.onclick=e=>e.target.closest('[data-value]')?.remove()});
}
