// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JSON keeps the persisted schema independent of generated UI model constructors.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function AppUpdateStatus(): $CancellablePromise<string> {
    return $Call.ByID(4221056084);
}

export function CheckAppUpdate(): $CancellablePromise<string> {
    return $Call.ByID(1644843250);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1660024404, id);
}

/**
 * CopyLogText is a legacy clipboard API also used by the server editor to
 * copy credentials. Keep its name and size limit for existing frontend calls.
 */
export function CopyLogText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(3943791706, text);
}

export function DownloadAppUpdate(): $CancellablePromise<string> {
    return $Call.ByID(3010648730);
}

export function ExportBackup(): $CancellablePromise<boolean> {
    return $Call.ByID(2057329072);
}

/**
 * An empty id exports every routing set, preserving their order.
 */
export function ExportRouteSets(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3044007522, id);
}

export function FetchSubscription(data: string): $CancellablePromise<string> {
    return $Call.ByID(3519107569, data);
}

export function ImportBackup(): $CancellablePromise<string> {
    return $Call.ByID(3273527047);
}

/**
 * ImportRouteSets only reads the file; the UI previews it before SaveConfig.
 */
export function ImportRouteSets(): $CancellablePromise<string> {
    return $Call.ByID(2815500263);
}

export function ImportYAML(): $CancellablePromise<string> {
    return $Call.ByID(1395516998);
}

export function InstallAppUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3166738271);
}

export function InstallCore(): $CancellablePromise<string> {
    return $Call.ByID(2173396360);
}

export function ListProcesses(): $CancellablePromise<string> {
    return $Call.ByID(4226576265);
}

export function LoadConfig(): $CancellablePromise<string> {
    return $Call.ByID(1280593290);
}

export function Logs(): $CancellablePromise<string> {
    return $Call.ByID(735830563);
}

/**
 * LogsLocation exposes the log writer's own directory, never a caller path.
 */
export function LogsLocation(): $CancellablePromise<string> {
    return $Call.ByID(832583476);
}

export function OpenExternalURL(address: string): $CancellablePromise<void> {
    return $Call.ByID(1286088376, address);
}

/**
 * OpenLogsFolder opens the directory in Explorer or Finder. Creating it first
 * makes the action useful before Mihomo has written its first log message.
 */
export function OpenLogsFolder(): $CancellablePromise<void> {
    return $Call.ByID(3193115311);
}

export function ParseServerLink(link: string): $CancellablePromise<string> {
    return $Call.ByID(3153887988, link);
}

export function PreviewYAML(): $CancellablePromise<string> {
    return $Call.ByID(2959623539);
}

export function ProcessIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(279038872, path);
}

export function RecoverProxy(): $CancellablePromise<void> {
    return $Call.ByID(2500727668);
}

export function ReloadConfig(): $CancellablePromise<void> {
    return $Call.ByID(3781955079);
}

export function SaveConfig(data: string): $CancellablePromise<string> {
    return $Call.ByID(2018231407, data);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2509819932);
}

export function Status(): $CancellablePromise<string> {
    return $Call.ByID(1775231042);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3588462264);
}

export function TestLatency(): $CancellablePromise<string> {
    return $Call.ByID(1407565166);
}

export function TestRunningServerLatency(id: string): $CancellablePromise<number> {
    return $Call.ByID(2286130018, id);
}

export function TestServerLatency(id: string): $CancellablePromise<number> {
    return $Call.ByID(1389475735, id);
}

export function UpdateSubscription(id: string): $CancellablePromise<string> {
    return $Call.ByID(755754096, id);
}

export function WorkPreset(): $CancellablePromise<string> {
    return $Call.ByID(1659646726);
}
