// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JSON keeps the persisted schema independent of generated UI model constructors.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(2089889390);
}

export function CloseConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1660024404, id);
}

export function CopyLogText(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(3943791706, text);
}

export function ExportBackup(): $CancellablePromise<boolean> {
    return $Call.ByID(2057329072);
}

export function ExportLogs(): $CancellablePromise<boolean> {
    return $Call.ByID(2705101069);
}

/**
 * An empty id exports every routing set, preserving their order.
 */
export function ExportRouteSets(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3044007522, id);
}

export function FetchSubscription(data: string): $CancellablePromise<string> {
    return $Call.ByID(3519107569, data);
}

export function ImportBackup(): $CancellablePromise<string> {
    return $Call.ByID(3273527047);
}

/**
 * ImportRouteSets only reads the file; the UI previews it before SaveConfig.
 */
export function ImportRouteSets(): $CancellablePromise<string> {
    return $Call.ByID(2815500263);
}

export function ImportYAML(): $CancellablePromise<string> {
    return $Call.ByID(1395516998);
}

export function InstallCore(): $CancellablePromise<string> {
    return $Call.ByID(2173396360);
}

export function ListProcesses(): $CancellablePromise<string> {
    return $Call.ByID(4226576265);
}

export function LoadConfig(): $CancellablePromise<string> {
    return $Call.ByID(1280593290);
}

export function Logs(): $CancellablePromise<string> {
    return $Call.ByID(735830563);
}

export function OpenExternalURL(address: string): $CancellablePromise<void> {
    return $Call.ByID(1286088376, address);
}

export function ParseServerLink(link: string): $CancellablePromise<string> {
    return $Call.ByID(3153887988, link);
}

export function PreviewYAML(): $CancellablePromise<string> {
    return $Call.ByID(2959623539);
}

export function ProcessIcon(path: string): $CancellablePromise<string> {
    return $Call.ByID(279038872, path);
}

export function RecoverProxy(): $CancellablePromise<void> {
    return $Call.ByID(2500727668);
}

/**
 * RequestElevation relaunches the app with administrator rights (Windows
 * only) so TUN can start. On success the app quits right away to free the
 * single-instance lock for the elevated replacement - see
 * Manager.RequestElevation and the --elevate-relaunch-helper handling in
 * main.go for the rest of the handoff.
 */
export function RequestElevation(resumeConnect: boolean): $CancellablePromise<void> {
    return $Call.ByID(1430237440, resumeConnect);
}

export function SaveConfig(data: string): $CancellablePromise<string> {
    return $Call.ByID(2018231407, data);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2509819932);
}

export function Status(): $CancellablePromise<string> {
    return $Call.ByID(1775231042);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3588462264);
}

export function TestLatency(): $CancellablePromise<string> {
    return $Call.ByID(1407565166);
}

export function TestRunningServerLatency(id: string): $CancellablePromise<number> {
    return $Call.ByID(2286130018, id);
}

export function TestServerLatency(id: string): $CancellablePromise<number> {
    return $Call.ByID(1389475735, id);
}

export function UpdateSubscription(id: string): $CancellablePromise<string> {
    return $Call.ByID(755754096, id);
}

export function WorkPreset(): $CancellablePromise<string> {
    return $Call.ByID(1659646726);
}
